### ISSUE TITLE
Crash after selecting language pt-BR

### ISSUE THREAD

**Issue by gatolenin** [blurymind/YarnClassic#263]
Hello

Excuse me the english "google translate". I'm a Twine user and wanted to try Yarn Editor. However, both in the browser and on the desktop version, the program stopped working after trying to change the language settings to pt-BR. In the Browser, it returned to work after clearing the cache of Google Chrome, but in the desktop version, not even uninstalling the program and reinstalling again worked.

Can anyone help me?

Thanks.

**Comment by mimecat** [comment]
I have the same problem. Also, sometimes working in english and resume saving the project, the text entirely disappears.

**Comment by blurymind** [comment]
So whenever you try to get an exotic language, yarn will try to download it from a location since it is not bundling it.
This will lock it up for a second initially,as it is downloading it.

Perhaps I should change this to instead get the languages from a user folder when on electron - but that would mean that you will have to download a BR dictionary file yourself and put it in a specific folder where yarn would expect it

**Comment by FaultyFunctions** [comment]
Hello I've run into this issue on my own fork of YarnEditor. It's actually not the downloading that locks up YarnEditor, the hunspell dictionary provided for the language just doesn't actually work. Something goes wrong when trying to parse it and nspell runs an infinite loop for some reason. In fact, a lot of the languages do this. Please see here for more information: https://github.com/wooorm/nspell/issues/11

Unfortunately I was unable to find a fix or a working dictionary for these languages so I had to remove them from the app. Here are the languages that didn't work for me and crashed the app:
* Afrikaans
* Indonesian
* Malay
* Catalan
* Basque
* Galician
* Croatian
* Zulu
* Italian
* Hungarian
* Portuguese
* Finnish
* Chinese
* Japanese
* Latin

Also just for the future, it would be best to refrain from calling other languages "exotic" as it can be seen as offensive. Obviously I know this isn't your intention, but just an FYI for the future.

**Comment by blurymind** [comment]
There is one easy way to fix this and it is in making the electron build
script copy these languages to the public folder. I have avoided adding all
languages to be a part of yarn, because they will massively increase the
deployment size of the web version.

But for electron, the size is huge anyways due to electron, so it
shouldnt matter much

**Comment by blurymind** [comment]
Another thing we can do is make the fetching of dictionaries an async event. Currently yarn will be blocked and freeze up while it downloads a dictionary, which is not great

**Comment by FaultyFunctions** [comment]
Again, the issue isn't retrieving these dictionaries from the web. The issue is `nspell` parsing these dictionaries. It would need a new updated dictionary for `nspell` to parse it properly, since `nspell`'s algorithm is hanging on something inside the dictionary files. Or as an alternative to use a different dictionary parser besides `nspell`.

**Comment by blurymind** [comment]
A different dictionary lib would be welcome too

**Comment by blurymind** [comment]
I am going to remove the problematic languages from our language selection for now - as a temporary fix to prevent people from crashing yarn

**Comment by blurymind** [comment]
> Hello I've run into this issue on my own fork of YarnEditor. It's actually not the downloading that locks up YarnEditor, the hunspell dictionary provided for the language just doesn't actually work. Something goes wrong when trying to parse it and nspell runs an infinite loop for some reason. In fact, a lot of the languages do this. Please see here for more information: [wooorm/nspell#11](https://github.com/wooorm/nspell/issues/11)
> 
> Unfortunately I was unable to find a fix or a working dictionary for these languages so I had to remove them from the app. Here are the languages that didn't work for me and crashed the app:
> 
> * Afrikaans
> * Indonesian
> * Malay
> * Catalan
> * Basque
> * Galician
> * Croatian
> * Zulu
> * Italian
> * Hungarian
> * Portuguese
> * Finnish
> * Chinese
> * Japanese
> * Latin
> 
> Also just for the future, it would be best to refrain from calling other languages "exotic" as it can be seen as offensive. Obviously I know this isn't your intention, but just an FYI for the future.

Some of these are not even listed as options in the settings :)

**Comment by blurymind** [comment]
There is an issue opened for ace-editor here too https://github.com/ajaxorg/ace/issues/2107 to add a native spellchecker

**Comment by blurymind** [comment]
it looks like the server yarn was fetching them from is now dead too. Will need to fix that :(

**Comment by blurymind** [comment]
I have now disabled the dictionaries that are reported to crash Yarn editor, also fixes the path for downloading dictionaries which has changed
